# Automatic Makefile made by make4js by N.J.M.

fgl_obj1 =  \
	 solve.$(4GLOBJ) \
	 calc_dist.$(4GLOBJ) \
	 db_connect.$(4GLOBJ)

fgl_obj2 =  \
	 ruins.$(4GLOBJ) \
	 calc_dist.$(4GLOBJ) \
	 db_connect.$(4GLOBJ)

fgl_frm1 = 

PRG1=solve.42r
PRG2=ruins.42r

include Make_fjs.inc

ed.sch:
	fgldbsch  -db "ed.db" -dv dbmsqt
